---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: lcls-airflow-dev--postgres-0
  labels:
    type: local
spec:
  storageClassName: lcls-airflow-dev--postgres
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  #hostPath:
  local:
    path: /gpfs/slac/cryo/fs1/daq/lcls/dev/database/postgres-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage/lcls
          operator: In
          values:
          - 'true'


#
